"""
Core numerics for qiskit-eigenlight.

Everything here is plain numpy: build a Hamiltonian (typically the adjacency
matrix of a Cayley graph Cay(Z_n, S)), diagonalize it, and derive two things
from the result:

  * `spectral_lines`   -- the Fourier decomposition of a probe observable's
                           expectation value, i.e. the "emission spectrum".
  * `ctqw_populations` -- the continuous-time quantum walk site-occupation
                           dynamics driven by that same Hamiltonian.

No dependency on Qiskit itself. This module only needs numpy.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from math import gcd
from typing import Iterable, Optional

import numpy as np

__all__ = [
    "build_cayley_adjacency",
    "girth",
    "spectral_gap",
    "SpectralLine",
    "spectral_lines",
    "ctqw_populations",
]


def build_cayley_adjacency(n: int, generators: Iterable[int]) -> np.ndarray:
    """Adjacency matrix of the circulant Cayley graph Cay(Z_n, S).

    `generators` is the generating set S (elements of Z_n \\ {0}; each s
    connects vertex i to i+s and i-s mod n). S is symmetrized automatically
    -- you do not need to pass both s and n-s.

    Parameters
    ----------
    n : group order (number of vertices), n >= 3.
    generators : iterable of ints in [1, n-1].

    Returns
    -------
    (n, n) float64 numpy array, symmetric, zero diagonal.
    """
    if n < 3:
        raise ValueError("n must be at least 3")
    gens = {g % n for g in generators if g % n != 0}
    if not gens:
        raise ValueError("generating set must contain at least one nonzero element")

    A = np.zeros((n, n), dtype=np.float64)
    idx = np.arange(n)
    for s in gens:
        j1 = (idx + s) % n
        j2 = (idx - s) % n
        A[idx, j1] = 1.0
        A[j1, idx] = 1.0
        A[idx, j2] = 1.0
        A[j2, idx] = 1.0
    np.fill_diagonal(A, 0.0)
    return A


def is_connected_cyclic(n: int, generators: Iterable[int]) -> bool:
    """True iff the generating set generates all of Z_n (graph is connected)."""
    gens = [g % n for g in generators if g % n != 0]
    if not gens:
        return n == 1
    g = n
    for s in gens:
        g = gcd(g, s)
    return g == 1


def girth(adjacency: np.ndarray) -> float:
    """Length of the shortest cycle in an undirected simple graph.

    Exact BFS-based computation (O(V * E)), fine for the graph sizes this
    package targets (tens of vertices). Returns float('inf') if acyclic.
    """
    n = adjacency.shape[0]
    best = float("inf")
    adj_list = [np.nonzero(adjacency[i])[0] for i in range(n)]

    for s in range(n):
        dist = [-1] * n
        parent = [-1] * n
        dist[s] = 0
        q = deque([s])
        while q:
            u = q.popleft()
            for v in adj_list[u]:
                v = int(v)
                if dist[v] == -1:
                    dist[v] = dist[u] + 1
                    parent[v] = u
                    q.append(v)
                elif v != parent[u]:
                    cyc = dist[u] + dist[v] + 1
                    if cyc < best:
                        best = cyc
    return best


def spectral_gap(eigenvalues: np.ndarray) -> float:
    """Difference between the largest and second-largest eigenvalue."""
    vals = np.sort(eigenvalues)
    if len(vals) < 2:
        return 0.0
    return float(vals[-1] - vals[-2])


@dataclass
class SpectralLine:
    k: int
    l: int
    freq: float
    amplitude: float
    normalized: float


def spectral_lines(
    H: np.ndarray,
    start_vertex: int,
    transition_operator: Optional[np.ndarray] = None,
) -> list[SpectralLine]:
    """Fourier-decompose <T(t)> under evolution generated by H, from a state
    localized at `start_vertex`.

    Each unordered eigenstate pair (k, l) contributes a spectral line at
    frequency omega_kl = |E_k - E_l| with amplitude 2*|c_k c_l <k|T|l>|,
    where c = V^T psi0 are the initial-state components in the eigenbasis.

    If `transition_operator` is None, a uniform all-pairs coupling is used
    (every pair of eigenstates is treated as equally allowed) -- see the
    README for why this is a stated simplification, not a physical claim.
    """
    n = H.shape[0]
    if not (0 <= start_vertex < n):
        raise ValueError("start_vertex out of range")

    evals, evecs = np.linalg.eigh(H)  # evecs columns are eigenvectors, real symmetric H

    if transition_operator is None:
        T = np.ones((n, n)) - np.eye(n)
    else:
        T = transition_operator

    B = evecs.T @ T @ evecs
    c = evecs[start_vertex, :]  # c_k = <k| start_vertex>

    lines: list[SpectralLine] = []
    for k in range(n):
        for l in range(k + 1, n):
            freq = abs(evals[l] - evals[k])
            amp = 2.0 * abs(c[k] * c[l] * B[k, l])
            lines.append(SpectralLine(k=k, l=l, freq=freq, amplitude=amp, normalized=0.0))

    max_amp = max((ln.amplitude for ln in lines), default=1e-9) or 1e-9
    for ln in lines:
        ln.normalized = ln.amplitude / max_amp

    return lines


def ctqw_populations(
    H: np.ndarray,
    start_vertex: int,
    t_max: Optional[float] = None,
    num_steps: int = 220,
):
    """Continuous-time quantum walk populations |psi_i(t)|^2 for a walk
    generated by H, starting localized at `start_vertex`.

    Returns (times, populations) where populations has shape
    (num_steps + 1, n).

    If `t_max` is not given, it's chosen from the smallest nonzero
    eigenvalue gap so the window covers a few periods of the slowest beat.
    """
    n = H.shape[0]
    evals, evecs = np.linalg.eigh(H)
    c = evecs[start_vertex, :]

    if t_max is None:
        gaps = np.abs(evals[:, None] - evals[None, :])
        nonzero = gaps[gaps > 1e-9]
        min_gap = nonzero.min() if nonzero.size else 1.0
        t_max = float(np.clip((2 * np.pi / min_gap) * 3, 5.0, 60.0))

    times = np.linspace(0.0, t_max, num_steps + 1)
    # psi(t)_i = sum_k V[i,k] c_k exp(-i E_k t)
    phase = np.exp(-1j * np.outer(times, evals))  # (steps, n_eig)
    coeffs = phase * c[None, :]                    # (steps, n_eig)
    psi_t = coeffs @ evecs.T                        # (steps, n_sites)
    populations = np.abs(psi_t) ** 2

    return times, populations
